### PR TITLE
feat(exclude): Add possibility of excluding files

### PR DESCRIPTION
**Pull request by nicojs**
* Add `exclude` and `mutateExclude` to `StrykerOptions`.
* Fill arrays in the `Config` class.

### CODE REVIEW

**Comment by simondel** [comment]
This may lead to some confusion. An InputFileDescriptor has the property `included`. If you set that to false that file would be excluded. Should that have the same behavior in the `TestFramework` as adding a file to `exclude`? Because right now the mocha-runner just ignores `include: false` files.

**Comment by nicojs** [comment]
Hmm interesting. Yes, the mocha-runner does not do anything with files with `included: false`, however those files will still be inside the `Sandbox`. This means that a test file can still import it, with `require('../src/MySourceFile')` for example. 

The exclude in this PR is something different. This exclude is comparable to [karma's exclude](http://karma-runner.github.io/1.0/config/configuration-file.html). So after resolving the input files, we remove the once resolved by the `exclude` patterns. Same goes for `mutateExclude`. This should fix [Stryker issue#95](https://github.com/stryker-mutator/stryker/issues/95)

What would you suggest as naming convention?

**Comment by nicojs** [comment]
Maybe `except` and `mutateExcept` are better names? Or `filesExcept` and `mutateExcept`?

**Comment by simondel** [comment]
Why should we need a separate property? Why don't we exclude files with a special character such as `!`.

You could for example have:
```
files: [
'test/**/*.js', 
'!test/integration/**/*.js', 
{ pattern: 'src/**/*.js', included: false, mutated: true }
],
```

The excluded files should be removed before the config is passed onto the TestFramework. That way the TestFramework won't have to know anything about excluding files.

**Comment by nicojs** [comment]
You mean `TestRunner`?

`!`  Is a valid character in paths. I agree its a stretch, but paths might start with that character.

**Comment by simondel** [comment]
Yeah, `TestRunner`, my bad. I think it's pretty standard to exclue files that way. If you really want to support people starting folder names with a `!` we could always build it so they could add an exclusion character such as a backslash

**Comment by nicojs** [comment]
So we execute the globbing expressions one by one. If an expression starts with an `!`, we remove the files, if it does not start with a `!` we add tge file. Sounds good. I will implement this when i have time.

**Comment by simondel** [comment]
Exactly! One final thing. Do we want toexclude the files after we have globbed everything so the order of files doesn't matter?

**Comment by nicojs** [comment]
I would say in the order you provide. That way we can support complex use cases like this one:

```javascript
files: ['**/*.js', '!**/index.js', '**/my-special-folder/index.js']
```

If a folder starts with a `!` we could allow for the full `InputFileDescription` syntax. For example:

```javascript
files: [{ pattern: '!src/*.js' }]
```

This does not need this PR, so i'm closing it.

**Pull request closed without merging**
